# Generated by Django 4.2.13 on 2024-05-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Main",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SALES",
            fields=[
                ("SALES_id", models.AutoField(primary_key=True, serialize=False)),
                ("subtype", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Email.main"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HR",
            fields=[
                ("HR_id", models.AutoField(primary_key=True, serialize=False)),
                ("subtype", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Email.main"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DEV",
            fields=[
                ("DEV_id", models.AutoField(primary_key=True, serialize=False)),
                ("subtype", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Email.main"
                    ),
                ),
            ],
        ),
    ]
